display/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('production.urls'))
    
]

production/urls.py
from django.urls import path
from django.http import HttpResponse
from production.views import list_production, production_started, change_status_production_to_started, concluded, change_status_production_concluded



app_name = 'productions'






urlpatterns = [
    path('',list_production,name='list_production'),
    path('started/', production_started, name = 'production_started'),
    path('change-to-started/',change_status_production_to_started, name='change-to-started'),
    path('concluded/', concluded, name='concluded'),
    path('change-started/',change_status_production_concluded, name='change-started'),
    
]

production/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Sb1010(models.Model):
    b1_afamad = models.FloatField(blank=True)
    b1_filial = models.CharField(max_length=2,blank=True)
    b1_cod = models.CharField(max_length=15,blank=True)
    b1_desc = models.CharField(max_length=34,blank=True)
    b1_codite = models.CharField(max_length=27,blank=True)
    b1_tipo = models.CharField(max_length=2,blank=True)
    b1_um = models.CharField(max_length=2,blank=True)
    b1_descing = models.CharField(max_length=78,blank=True)
    b1_locpad = models.CharField(max_length=2,blank=True)
    b1_grupo = models.CharField(max_length=4,blank=True)
    b1_picm = models.FloatField(blank=True)
    b1_posipi = models.CharField(max_length=10,blank=True)
    b1_especie = models.CharField(max_length=2,blank=True)
    b1_ex_ncm = models.CharField(max_length=3,blank=True)
    b1_ex_nbm = models.CharField(max_length=3,blank=True)
    b1_ipi = models.FloatField(blank=True)
    b1_aliqiss = models.FloatField(blank=True)
    b1_codiss = models.CharField(max_length=9,blank=True)
    b1_te = models.CharField(max_length=3,blank=True)
    b1_ts = models.CharField(max_length=3,blank=True)
    b1_picmret = models.FloatField(blank=True)
    b1_picment = models.FloatField(blank=True)
    b1_bitmap = models.CharField(max_length=20,blank=True)
    b1_segum = models.CharField(max_length=2,blank=True)
    b1_impzfrc = models.CharField(max_length=1,blank=True)
    b1_conv = models.FloatField(blank=True)
    b1_tipconv = models.CharField(max_length=1,blank=True)
    b1_alter = models.CharField(max_length=15,blank=True)
    b1_qe = models.FloatField(blank=True)
    b1_prv1 = models.FloatField(blank=True)
    b1_emin = models.FloatField(blank=True)
    b1_custd = models.FloatField(blank=True)
    b1_ucalstd = models.CharField(max_length=8,blank=True)
    b1_uprc = models.FloatField(blank=True)
    b1_ucom = models.CharField(max_length=8,blank=True)
    b1_mcustd = models.CharField(max_length=1,blank=True)
    b1_peso = models.FloatField(blank=True)
    b1_estfor = models.CharField(max_length=3,blank=True)
    b1_estseg = models.FloatField(blank=True)
    b1_forprz = models.CharField(max_length=3,blank=True)
    b1_pe = models.FloatField(blank=True)
    b1_tipe = models.CharField(max_length=1,blank=True)
    b1_le = models.FloatField(blank=True)
    b1_lm = models.FloatField(blank=True)
    b1_conta = models.CharField(max_length=20,blank=True)
    b1_toler = models.FloatField(blank=True)
    b1_cc = models.CharField(max_length=9,blank=True)
    b1_itemcc = models.CharField(max_length=9,blank=True)
    b1_familia = models.CharField(max_length=1,blank=True)
    b1_qb = models.FloatField(blank=True)
    b1_lojproc = models.CharField(max_length=2,blank=True)
    b1_proc = models.CharField(max_length=6,blank=True)
    b1_apropri = models.CharField(max_length=1,blank=True)
    b1_tipodec = models.CharField(max_length=1,blank=True)
    b1_origem = models.CharField(max_length=1,blank=True)
    b1_clasfis = models.CharField(max_length=2,blank=True)
    b1_fantasm = models.CharField(max_length=1,blank=True)
    b1_urev = models.CharField(max_length=8,blank=True)
    b1_datref = models.CharField(max_length=8,blank=True)
    b1_rastro = models.CharField(max_length=1,blank=True)
    b1_foraest = models.CharField(max_length=1,blank=True)
    b1_comis = models.FloatField(blank=True)
    b1_mono = models.CharField(max_length=1,blank=True)
    b1_dtrefp1 = models.CharField(max_length=8,blank=True)
    b1_perinv = models.FloatField(blank=True)
    b1_grtrib = models.CharField(max_length=6,blank=True)
    b1_mrp = models.CharField(max_length=1,blank=True)
    b1_notamin = models.FloatField(blank=True)
    b1_prvalid = models.FloatField(blank=True)
    b1_conini = models.CharField(max_length=8,blank=True)
    b1_contsoc = models.CharField(max_length=1,blank=True)
    b1_numcop = models.FloatField(blank=True)
    b1_codbar = models.CharField(max_length=15,blank=True)
    b1_irrf = models.CharField(max_length=1,blank=True)
    b1_grade = models.CharField(max_length=1,blank=True)
    b1_formlot = models.CharField(max_length=3,blank=True)
    b1_fpcod = models.CharField(max_length=10,blank=True)
    b1_codgtin = models.CharField(max_length=15,blank=True)
    b1_localiz = models.CharField(max_length=1,blank=True)
    b1_desc_p = models.CharField(max_length=6,blank=True)
    b1_contrat = models.CharField(max_length=1,blank=True)
    b1_desc_gi = models.CharField(max_length=6,blank=True)
    b1_desc_i = models.CharField(max_length=6,blank=True)
    b1_operpad = models.CharField(max_length=2,blank=True)
    b1_vlrefus = models.FloatField(blank=True)
    b1_opc = models.CharField(max_length=80,blank=True)
    b1_anuente = models.CharField(max_length=1,blank=True)
    b1_codobs = models.CharField(max_length=6,blank=True)
    b1_import = models.CharField(max_length=1,blank=True)
    b1_fabric = models.CharField(max_length=20,blank=True)
    b1_sitprod = models.CharField(max_length=2,blank=True)
    b1_modelo = models.CharField(max_length=15,blank=True)
    b1_setor = models.CharField(max_length=2,blank=True)
    b1_balanca = models.CharField(max_length=1,blank=True)
    b1_prodpai = models.CharField(max_length=15,blank=True)
    b1_tecla = models.CharField(max_length=3,blank=True)
    b1_emax = models.FloatField(blank=True)
    b1_tipocq = models.CharField(max_length=1,blank=True)
    b1_solicit = models.CharField(max_length=1,blank=True)
    b1_quadpro = models.CharField(max_length=1,blank=True)
    b1_agregcu = models.CharField(max_length=1,blank=True)
    b1_base3 = models.CharField(max_length=14,blank=True)
    b1_grupcom = models.CharField(max_length=6,blank=True)
    b1_despimp = models.CharField(max_length=1,blank=True)
    b1_desbse3 = models.CharField(max_length=60,blank=True)
    b1_numcqpr = models.FloatField(blank=True)
    b1_contcqp = models.FloatField(blank=True)
    b1_pesbru = models.FloatField(blank=True)
    b1_observa = models.CharField(max_length=78,blank=True)
    b1_revatu = models.CharField(max_length=3,blank=True)
    b1_inss = models.CharField(max_length=1,blank=True)
    b1_codemb = models.CharField(max_length=30,blank=True)
    b1_especif = models.CharField(max_length=80,blank=True)
    b1_mat_pri = models.CharField(max_length=20,blank=True)
    b1_nalncca = models.CharField(max_length=7,blank=True)
    b1_redinss = models.FloatField(blank=True)
    b1_redirrf = models.FloatField(blank=True)
    b1_nalsh = models.CharField(max_length=8,blank=True)
    b1_aladi = models.CharField(max_length=3,blank=True)
    b1_tab_ipi = models.CharField(max_length=2,blank=True)
    b1_grudes = models.CharField(max_length=3,blank=True)
    b1_redpis = models.FloatField(blank=True)
    b1_redcof = models.FloatField(blank=True)
    b1_datasub = models.CharField(max_length=8,blank=True)
    b1_pcsll = models.FloatField(blank=True)
    b1_pcofins = models.FloatField(blank=True)
    b1_ppis = models.FloatField(blank=True)
    b1_mtbf = models.FloatField(blank=True)
    b1_mttr = models.FloatField(blank=True)
    b1_flagsug = models.CharField(max_length=1,blank=True)
    b1_classve = models.CharField(max_length=1,blank=True)
    b1_midia = models.CharField(max_length=1,blank=True)
    b1_qtmidia = models.FloatField(blank=True)
    b1_vlr_ipi = models.FloatField(blank=True)
    b1_envobr = models.CharField(max_length=1,blank=True)
    b1_qtdser = models.CharField(max_length=1,blank=True)
    b1_serie = models.CharField(max_length=20,blank=True)
    b1_faixas = models.FloatField(blank=True)
    b1_nropag = models.FloatField(blank=True)
    b1_isbn = models.CharField(max_length=10,blank=True)
    b1_titorig = models.CharField(max_length=50,blank=True)
    b1_lingua = models.CharField(max_length=20,blank=True)
    b1_edicao = models.CharField(max_length=3,blank=True)
    b1_obsisbn = models.CharField(max_length=40,blank=True)
    b1_clvl = models.CharField(max_length=9,blank=True)
    b1_ativo = models.CharField(max_length=1,blank=True)
    b1_tipcar = models.CharField(max_length=6,blank=True)
    b1_alfumac = models.FloatField(blank=True)
    b1_admin = models.CharField(max_length=10,blank=True)
    b1_ulocpd = models.CharField(max_length=2,blank=True)
    b1_qtdconf = models.FloatField(blank=True)
    b1_fracper = models.FloatField(blank=True)
    b1_int_icm = models.FloatField(blank=True)
    b1_vlr_icm = models.FloatField(blank=True)
    b1_vlrselo = models.FloatField(blank=True)
    b1_codnor = models.CharField(max_length=3,blank=True)
    b1_corpri = models.CharField(max_length=6,blank=True)
    b1_corsec = models.CharField(max_length=6,blank=True)
    b1_nicone = models.CharField(max_length=15,blank=True)
    b1_atrib1 = models.CharField(max_length=6,blank=True)
    b1_atrib2 = models.CharField(max_length=6,blank=True)
    b1_atrib3 = models.CharField(max_length=6,blank=True)
    b1_regseq = models.CharField(max_length=6,blank=True)
    b1_cpotenc = models.CharField(max_length=1,blank=True)
    b1_potenci = models.FloatField(blank=True)
    b1_qtdacum = models.FloatField(blank=True)
    b1_qtdinic = models.FloatField(blank=True)
    b1_requis = models.CharField(max_length=1,blank=True)
    b1_selo = models.CharField(max_length=1,blank=True)
    b1_lotven = models.FloatField(blank=True)
    b1_ok = models.CharField(max_length=4,blank=True)
    b1_usafefo = models.CharField(max_length=1,blank=True)
    b1_iat = models.CharField(max_length=1,blank=True)
    b1_ippt = models.CharField(max_length=1,blank=True)

production/views.py
from django.shortcuts import render, redirect
from production.models import  Sd3010
from django.db import connection
from django.contrib import messages





from django.urls import path


# Retorna os valores das colunas da Home
def list_production(request):
   
    

    #Retorna os valores da coluna dos elementos criados
    with connection.cursor() as cursor:
        cursor.execute( """select d3_cod,b1_desc,d3_lotectl,substr(d3_emissao,7,2)||'/'||substr(d3_emissao,5,2)||'/'||substr(d3_emissao,1,4) from sd3010,sb1010 where b1_cod=d3_cod and d3_quant=0 and d3_tm='100' and sd3010.d_e_l_e_t_<>'*' and d3_lotectl not in (select d3_loteprt from sd3010 where  d3_loteprt<>'' and sd3010.d_e_l_e_t_<>'*' group by d3_loteprt) order by substr(d3_op,9,3) desc;""")
        not_started = cursor.fetchall()
   
 
    
   
   
    #Retorna os valores da coluna dos elementos iniciados
    with connection.cursor() as cursor:
        cursor.execute( """select d3_cod,b1_desc,d3_lotectl,substr(d3_emissao,7,2)||'/'||substr(d3_emissao,5,2)||'/'||substr(d3_emissao,1,4) from sd3010,sb1010 where b1_cod=d3_cod and d3_quant=0 and d3_tm='100' and sd3010.d_e_l_e_t_<>'*' and d3_lotectl in (select d3_loteprt from sd3010 where d3_loteprt<>'' and sd3010.d_e_l_e_t_<>'*' group by d3_loteprt) order by substr(d3_op,9,3) desc;""")
        started = cursor.fetchall()

      

    #Retorna os valores da coluna dos elementos concluídos
    with connection.cursor() as cursor:
        cursor.execute( """select d3_cod,b1_desc,d3_lotectl,substr(d3_emissao,7,2)||'/'||substr(d3_emissao,5,2)||'/'||substr(d3_emissao,1,4)  from sd3010,sb1010 where b1_cod=d3_cod and d3_emissao>='20230801' and d3_quant>0 and d3_tm='100' and sd3010.d_e_l_e_t_<>'*' order by substr(d3_op,9,3) desc;""")
        concluded = cursor.fetchall()

    
    
    return render(request,'production/list.html', context={'not_started':not_started, 'started':started, 'concluded':concluded,}
)




#Busca e retorna os valores para a página dos produtos criados
def production_started(request):

    with connection.cursor() as cursor:
        cursor.execute( """select d3_cod,b1_desc,d3_lotectl,substr(d3_emissao,7,2)||'/'||substr(d3_emissao,5,2)||'/'||substr(d3_emissao,1,4) from sd3010,sb1010 where b1_cod=d3_cod and d3_quant=0 and d3_tm='100' and sd3010.d_e_l_e_t_<>'*' and d3_lotectl not in (select d3_loteprt from sd3010 where  d3_loteprt<>'' and sd3010.d_e_l_e_t_<>'*' group by d3_loteprt) order by substr(d3_op,9,3) desc;""")
        not_started = cursor.fetchall()
   


    return render(request, 'production/criados.html', context={'not_started':not_started,})


#Implementação das condições para o elemento mudar de status no banco de dados
def change_status_production_to_started(request):
    if request.method == 'POST':
        cod_production=request.POST.get('code_product_not_started', '')
        if cod_production=='':
             list(messages.get_messages(request))
             messages.error(request,'Não é permitido um valor vazio')
        else:
            try:
                
                
                sd3010 = Sd3010.objects.filter(d3_lotectl=cod_production).first()
                sd3010.d3_loteprt = cod_production
                sd3010.save()
                list(messages.get_messages(request))
                messages.success(request,'Produto iniciado com sucesso')
                
                
            except:
                list(messages.get_messages(request))
                messages.error(request,'Produto não encontrado')
        
        return redirect('productions:production_started')
    
    raise Exception('Não é permitido o método get')



#Busca e retorna os valores para a página dos produtos iniciados
def concluded(request):

    with connection.cursor() as cursor:
        cursor.execute("""select d3_cod,b1_desc,d3_lotectl,substr(d3_emissao,7,2)||'/'||substr(d3_emissao,5,2)||'/'||substr(d3_emissao,1,4) from sd3010,sb1010 where b1_cod=d3_cod and d3_quant=0 and d3_tm='100' and sd3010.d_e_l_e_t_<>'*' and d3_lotectl in (select d3_loteprt from sd3010 where d3_loteprt<>'' and sd3010.d_e_l_e_t_<>'*' group by d3_loteprt) order by substr(d3_op,9,3) desc;""")
        started = cursor.fetchall()
   


    return render(request, 'production/iniciados.html', context={'started':started,})


#Implementação das condições para o elemento mudar de status no banco de dados
def change_status_production_concluded(request):
    if request.method == 'POST':
        cod_production=request.POST.get('code_product_started', '')
        if cod_production=='':
            list(messages.get_messages(request))
            messages.error(request,'Não é permitido um valor vazio')
        else:
            try:
                
            
                sd3010 = Sd3010.objects.filter(d3_lotectl=cod_production).first()
                sd3010.d3_emissao ='20230802' 
                sd3010.d3_quant ='1'
                sd3010.save()
                list(messages.get_messages(request))
                messages.success(request,'Produto iniciado com sucesso')


                
            except:
                list(messages.get_messages(request))
                messages.error(request,'Produto não encontrado')
                
        return redirect('productions:concluded')
    

    raise Exception('not permission method get')

production/templates/production/criados.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/criados.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <title>Setor de Crição de produtos</title>
</head>

<body>

    <header class="header-container">
       
        <h1 class="title">Setor de Iniciação</h1>

        
    </header> 
    
    <main>

        <di>
            <a class="nav" href="{% url 'productions:list_production'  %}">
                <span>Home</span>
            </a>
    
            <a class="nav" href="{% url 'productions:concluded'  %}">
                <span> Setor De Conclusão</span>
            </a>
        </di>


        <table class="table-container" id="minhaTabela">
            <tr>
                <th class="th">Produtos disponíveis para se iniciar:</th>

            </tr>
            <tr class="teste">
                <td class="time">
                    <ul class="ul">
                        {% for tupla in not_started %}
                        <li class="row">{{ tupla.2 }}</li>
                        
                        {% endfor %}
                    </ul>
                </td>
            </tr>

        </table>
    </main>

    <form method="post" action='{% url "productions:change-to-started" %}' >
        {% csrf_token %}
        <div class="label-container">
            <label >Insira o produto a ser iniciado : </label>          
        </div>

        <div class="button-container">
            <input class="input" name = 'code_product_not_started' type="text"   placeholder="AUTO...">
            <button type="submit" class="button"><i class="fa-solid fa-check"></i></button>
          
        </div> 
        {% include "production/partials/messages.html" %}  
    </form>
</body>

</html>

production/templates/production/iniciados.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/criados.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <title>Setor de Crição de produtos</title>
</head>

<body>

    <header class="header-container">
       
        <h1 class="title">Setor de Conclusão</h1>

        
    </header> 

    <main>

        <di>
            <a class="nav" href="{% url 'productions:list_production'  %}">
                <span>Home</span>
            </a>
    
            <a class="nav" href="{% url 'productions:production_started'  %}">
                <span> Setor De Iniciação</span>
            </a>
        </di>
    
    
        <table class="table-container" id="minhaTabela">
            <tr>
                <th class="th">Produtos disponíveis para se iniciar:</th>

            </tr>
            <tr class="teste">
                <td class="time">
                    <ul class="ul">
                        {% for tupla in started %}
                        <li class="row">{{ tupla.2 }}</li>
                        
                        {% endfor %}
                    </ul>
                </td>
            </tr>

        </table>
    </main>

    <form method="post" action='{% url "productions:change-started" %}' >
        {% csrf_token %}
        <div class="label-container">
            <label >Insira o produto para ser concluído : </label>          
        </div>

        <div class="button-container">
            <input class="input" name = 'code_product_started' type="text"   placeholder="AUTO...">
            <button type="submit" class="button"><i class="fa-solid fa-check"></i></button>

           
          
        </div> 
        {% include "production/partials/messages.html" %}        
    </form>
</body>

</html>

production/templates/production/list.html
{% load static %}
<!DOCTYPE html>
<html lang="PT-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Teste</title>


</head>


<body class="body">

    <header class="header-container">
       
        <h1 class="title">Todos os Produtos</h1>

        
    </header> 
    


    <main class="main-container">

        <di>
            <a class="nav" href="{% url 'productions:production_started'  %}">
                <span>Setor De Iniciação</span>
            </a>
    
            <a class="nav" href="{% url 'productions:concluded'  %}">
                <span> Setor De Conlusão</span>
            </a>
        </di>
        



        <table class="table-container" id="minhaTabela">
            <tr>
                <th class="th">CRIADOS</th>
                <th class="th">INICIADOS</th>
                <th class="th">CONCLUÍDOS</th>
            </tr>
            <tr class="teste">
                <td class="time">
                    <ul class="ul">
                        {% for tupla in not_started %}
                        <li class="row">{{ tupla.2 }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td class="time">
                    <ul class="ul">
                        {% for tupla in started %}
                        <li class="row">{{ tupla.2 }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td class="time">
                    <ul class="ul">
                        {% for tupla in concluded %}
                        <li class="row">{{ tupla.2 }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </table>


    </main>

    <footer class="footer">
        <h4>
            Desenvolvido para fins práticos
        </h4>
        <h6>
            by: João Pereira
        </h6>
    </footer>





    <script src="{% static 'js/script.js' %}"></script>
</body>